# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51331d1941356dde617748a67b3f70769c6eea53bb0d1372b8cf7e3be288215ef7d8c0ca9a0d96cc7bfc58880493f3446529e3ac1f0c6cf9f2d84996daa0f456

test:
  secret_key_base: eb5864223802042a28f56393a29fdcba3a09dd377261b9c0776f865e1141a853819be2513ab33712eae43aa1b02a9cde9ec326af2cb0a16fa97ca742b9dd2c1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
